swagger: "2.0"
info:
  description: OrderHistory
  version: "1.0.0"
  title: API-OrderHistory
host: [path_3].wangbo.com
basePath: /clouddb01
paths:
  /orderHistory:
    post:
      summary: 增加OrderHistory
      parameters:
      - in: body
        name: body
        description: OrderHistory实体
        required: true
        schema:
          $ref: "#/definitions/OrderHistory"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: OrderHistory全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiOrderHistoryListResponse'
  /orderHistory/{orderHistoryId}:
    get:
      summary: 根据ID查询orderHistory
      parameters:
        - name: orderHistoryId
          in: path
          description: OrderHistoryID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiOrderHistoryResponse'
    put:
      summary: 修改OrderHistory
      parameters:
        - name: orderHistoryId
          in: path
          description: OrderHistoryID
          required: true
          type: string
        - name: body
          in: body
          description: OrderHistory实体
          required: true
          schema:
            $ref: "#/definitions/OrderHistory"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除OrderHistory
      parameters:
        - name: orderHistoryId
          in: path
          description: OrderHistoryID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /orderHistory/search:
    post:
      summary: 根据条件查询OrderHistory列表 
      parameters:
        - name: body
          in: body
          description: OrderHistory实体类
          required: true
          schema:
            $ref: '#/definitions/OrderHistory'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiOrderHistoryListResponse'
  /orderHistory/search/{page}/{size}:
    post:
      summary: OrderHistory分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/OrderHistory"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiOrderHistoryPageResponse'
definitions:
  OrderHistory:
    type: "object"
    properties:
      order_history_id:
        type: "string"        
        description: ""
      order_id:
        type: "string"        
        description: ""
      time:
        type: "string"        
        description: ""
      order_status:
        type: "string"        
        description: ""
      comment:
        type: "string"        
        description: ""
      customer_notified:
        type: "string"        
        description: ""

  OrderHistoryList:
    type: "array"
    items: 
      $ref: '#/definitions/OrderHistory'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiOrderHistoryResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/OrderHistory'
  ApiOrderHistoryListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/OrderHistoryList'
  ApiOrderHistoryPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/OrderHistoryList'
