swagger: "2.0"
info:
  description: OrderDetail
  version: "1.0.0"
  title: API-OrderDetail
host: [path_3].wangbo.com
basePath: /clouddb01
paths:
  /orderDetail:
    post:
      summary: 增加OrderDetail
      parameters:
      - in: body
        name: body
        description: OrderDetail实体
        required: true
        schema:
          $ref: "#/definitions/OrderDetail"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: OrderDetail全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiOrderDetailListResponse'
  /orderDetail/{orderDetailId}:
    get:
      summary: 根据ID查询orderDetail
      parameters:
        - name: orderDetailId
          in: path
          description: OrderDetailID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiOrderDetailResponse'
    put:
      summary: 修改OrderDetail
      parameters:
        - name: orderDetailId
          in: path
          description: OrderDetailID
          required: true
          type: string
        - name: body
          in: body
          description: OrderDetail实体
          required: true
          schema:
            $ref: "#/definitions/OrderDetail"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除OrderDetail
      parameters:
        - name: orderDetailId
          in: path
          description: OrderDetailID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /orderDetail/search:
    post:
      summary: 根据条件查询OrderDetail列表 
      parameters:
        - name: body
          in: body
          description: OrderDetail实体类
          required: true
          schema:
            $ref: '#/definitions/OrderDetail'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiOrderDetailListResponse'
  /orderDetail/search/{page}/{size}:
    post:
      summary: OrderDetail分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/OrderDetail"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiOrderDetailPageResponse'
definitions:
  OrderDetail:
    type: "object"
    properties:
      order_id:
        type: "string"        
        description: ""
      ship_method:
        type: "string"        
        description: ""
      ship_address:
        type: "string"        
        description: ""
      ship_price:
        type: "string"        
        description: ""
      pay_method:
        type: "string"        
        description: ""
      invoice_address:
        type: "string"        
        description: ""
      invoice_price:
        type: "string"        
        description: ""
      comment:
        type: "string"        
        description: ""
      order_products:
        type: "string"        
        description: ""

  OrderDetailList:
    type: "array"
    items: 
      $ref: '#/definitions/OrderDetail'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiOrderDetailResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/OrderDetail'
  ApiOrderDetailListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/OrderDetailList'
  ApiOrderDetailPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/OrderDetailList'
