swagger: "2.0"
info:
  description: Order
  version: "1.0.0"
  title: API-Order
host: [path_3].wangbo.com
basePath: /clouddb01
paths:
  /order:
    post:
      summary: 增加Order
      parameters:
      - in: body
        name: body
        description: Order实体
        required: true
        schema:
          $ref: "#/definitions/Order"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: Order全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiOrderListResponse'
  /order/{orderId}:
    get:
      summary: 根据ID查询order
      parameters:
        - name: orderId
          in: path
          description: OrderID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiOrderResponse'
    put:
      summary: 修改Order
      parameters:
        - name: orderId
          in: path
          description: OrderID
          required: true
          type: string
        - name: body
          in: body
          description: Order实体
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除Order
      parameters:
        - name: orderId
          in: path
          description: OrderID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /order/search:
    post:
      summary: 根据条件查询Order列表 
      parameters:
        - name: body
          in: body
          description: Order实体类
          required: true
          schema:
            $ref: '#/definitions/Order'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiOrderListResponse'
  /order/search/{page}/{size}:
    post:
      summary: Order分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/Order"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiOrderPageResponse'
definitions:
  Order:
    type: "object"
    properties:
      order_id:
        type: "string"        
        description: ""
      customer_id:
        type: "string"        
        description: ""
      status:
        type: "string"        
        description: ""
      total_price:
        type: "string"        
        description: ""
      reword_points:
        type: "string"        
        description: ""
      create_time:
        type: "string"        
        description: ""
      update_time:
        type: "string"        
        description: ""

  OrderList:
    type: "array"
    items: 
      $ref: '#/definitions/Order'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiOrderResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/Order'
  ApiOrderListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/OrderList'
  ApiOrderPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/OrderList'
