swagger: "2.0"
info:
  description: Product
  version: "1.0.0"
  title: API-Product
host: [path_3].wangbo.com
basePath: /clouddb01
paths:
  /product:
    post:
      summary: 增加Product
      parameters:
      - in: body
        name: body
        description: Product实体
        required: true
        schema:
          $ref: "#/definitions/Product"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    get:
      summary: Product全部列表
      responses:
        200:
          description: 成功
          schema: 
            $ref: '#/definitions/ApiProductListResponse'
  /product/{productId}:
    get:
      summary: 根据ID查询product
      parameters:
        - name: productId
          in: path
          description: ProductID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiProductResponse'
    put:
      summary: 修改Product
      parameters:
        - name: productId
          in: path
          description: ProductID
          required: true
          type: string
        - name: body
          in: body
          description: Product实体
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
    delete:
      summary: 根据ID删除Product
      parameters:
        - name: productId
          in: path
          description: ProductID
          required: true
          type: string
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiResponse'
  /product/search:
    post:
      summary: 根据条件查询Product列表 
      parameters:
        - name: body
          in: body
          description: Product实体类
          required: true
          schema:
            $ref: '#/definitions/Product'
      responses:
        200:
          description: 成功
          schema:
            $ref: '#/definitions/ApiProductListResponse'
  /product/search/{page}/{size}:
    post:
      summary: Product分页
      parameters:
        - name: page
          in: path
          description: 页码
          required: true
          type: integer
          format: int32
        - name: size
          in: path
          description: 页大小
          required: true
          type: integer
          format: int32
        - name: body
          in: body
          description: 查询条件
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        200:
          description: 查询成功
          schema:
            $ref: '#/definitions/ApiProductPageResponse'
definitions:
  Product:
    type: "object"
    properties:
      product_id:
        type: "string"        
        description: ""
      product_code:
        type: "string"        
        description: ""
      product_name:
        type: "string"        
        description: ""
      product_abstract:
        type: "string"        
        description: ""
      price:
        type: "string"        
        description: ""
      discount:
        type: "string"        
        description: ""
      stock_quantity:
        type: "string"        
        description: ""
      status:
        type: "string"        
        description: ""
      main_pic_url:
        type: "string"        
        description: ""
      reword_points:
        type: "string"        
        description: ""
      sort_order:
        type: "string"        
        description: ""

  ProductList:
    type: "array"
    items: 
      $ref: '#/definitions/Product'
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
  ApiProductResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/Product'
  ApiProductListResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        $ref: '#/definitions/ProductList'
  ApiProductPageResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      flag:
        type: "boolean"
      message:
        type: "string"
      data:
        properties:
          total:
            type: "integer"
            format: "int32"
          rows:
            $ref: '#/definitions/ProductList'
